server.port=8081
spring.application.name=payment-service

# Database Configuration (Cambiado a H2 para asegurar que funcione)
spring.datasource.url=jdbc:h2:mem:paymentdb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true

# Service Communication
app.user-service.url=http://localhost:8080/users
