server.port=8081
spring.application.name=payment-service

# Database Configuration (Cambiado a PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/voicepay_payment
spring.datasource.username=postgres
spring.datasource.password=ToPo12345@
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.h2.console.enabled=true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# Service Communication
app.user-service.url=http://localhost:8080/users
app.notification-service.url=http://localhost:8083/notifications

# Encryption
app.encryption-key=v0ic3P4yS3cur3Key2026Encryption!
