# HashiCorp Vault Integration
spring.application.name=user-service
spring.config.import=optional:vault://
spring.cloud.vault.uri=${VAULT_URI:http://localhost:8200}
spring.cloud.vault.token=${VAULT_TOKEN:my-root-token}
spring.cloud.vault.kv.enabled=true
spring.cloud.vault.config.lifecycle.enabled=true

# Database Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/voicepay_user}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:ToPo12345@}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Permite que Hibernate cree las tablas ANTES de ejecutar data.sql en los tests (H2)
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always


# Seguridad - API Key (Usando variable de entorno para seguridad)

# OAuth2 Google
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID:434775575216-dc98s5skkmviavd39s3mrnad0nartork.apps.googleusercontent.com}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=profile,email

# OAuth2 Microsoft (Azure AD)
spring.security.oauth2.client.registration.microsoft.client-id=${MICROSOFT_CLIENT_ID:YOUR_MICROSOFT_CLIENT_ID}
spring.security.oauth2.client.registration.microsoft.client-secret=${MICROSOFT_CLIENT_SECRET:YOUR_MICROSOFT_CLIENT_SECRET}
spring.security.oauth2.client.registration.microsoft.scope=openid,profile,email,User.Read
spring.security.oauth2.client.registration.microsoft.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.microsoft.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.cloud.vault.kv.profile-separator=/
spring.security.oauth2.client.provider.microsoft.authorization-uri=https://login.microsoftonline.com/common/oauth2/v2.0/authorize
spring.security.oauth2.client.provider.microsoft.token-uri=https://login.microsoftonline.com/common/oauth2/v2.0/token
spring.security.oauth2.client.provider.microsoft.user-info-uri=https://graph.microsoft.com/v1.0/me
spring.security.oauth2.client.provider.microsoft.user-name-attribute=displayName

# Encryption
app.encryption-key=${app.encryption-key:v0ic3P4yS3cur3Key2026Encryption!}

# Actuator & Prometheus Monitoring Configuration
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
management.prometheus.metrics.export.enabled=true
