spring.application.name=user-service

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/voicepay_db
spring.datasource.username=voicepay_user
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Permite que Hibernate cree las tablas ANTES de ejecutar data.sql en los tests (H2)
spring.jpa.defer-datasource-initialization=true
