apiVersion: v1
kind: ConfigMap
metadata:
  name: voicepay-configmap
  namespace: voicepay
data:
  SPRING_DATASOURCE_URL_USER: "jdbc:postgresql://voicepay-postgres:5432/voicepay_user"
  SPRING_DATASOURCE_URL_PAYMENT: "jdbc:postgresql://voicepay-postgres:5432/voicepay_payment"
  SPRING_DATASOURCE_URL_IVR: "jdbc:postgresql://voicepay-postgres:5432/voicepay_ivr"
  SPRING_DATASOURCE_URL_NOTIFICATION: "jdbc:postgresql://voicepay-postgres:5432/voicepay_notification"
  
  # Base URLs for Gateway
  USER_SERVICE_URL_BASE: "http://user-service:8080"
  PAYMENT_SERVICE_URL_BASE: "http://payment-service:8081"
  IVR_SERVICE_URL_BASE: "http://ivr-service:8082"
  NOTIFICATION_SERVICE_URL_BASE: "http://notification-service:8083"
  
  # Endpoint-specific URLs for inter-service communication
  USER_SERVICE_URL_USERS: "http://user-service:8080/users"
  PAYMENT_SERVICE_URL_PAYMENTS: "http://payment-service:8081/payments"
  NOTIFICATION_SERVICE_URL_NOTIFICATIONS: "http://notification-service:8083/notifications"
  
  LOGSTASH_HOST: "logstash"
