apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: voicepay-ingress
  namespace: voicepay
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: "16m"
spec:
  rules:
    - host: api.voicepay.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gateway-service
                port:
                  number: 9000
