apiVersion: v1
kind: Secret
metadata:
  name: voicepay-secrets
  namespace: voicepay
type: Opaque
data:
  postgres-username: cG9zdGdyZXM=
  postgres-password: VG9QbzEyMzQ1QA==
  google-client-id: NDM0Nzc1NTc1MjE2LWRjOThzNXNra212aWF2ZDM5czNtcm5hZDBuYXJ0b3JrLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29t
  google-client-secret: cGxhY2Vob2xkZXItZ29vZ2xlLXNlY3JldA==
  microsoft-client-id: WU9VUl9NSUNST1NPRlRfQ0xJRU5UX0lE
  microsoft-client-secret: WU9VUl9NSUNST1NPRlRfQ0xJRU5UX1NFQ1JFVA==
  encryption-key: djBpYzNQPDR5UzNjdXJlS2V5MjAyNkVuY3J5cHRpb24h
